# Generated by Django 2.2.6 on 2019-10-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0002_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
